//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int Ma_TK { get; set; }
        public string Ten_Dang_Nhap { get; set; }
        public string Mat_Khau { get; set; }
        public string Ma_NV { get; set; }
        public int Ma_VT { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual VAITRO_QUYEN VAITRO_QUYEN { get; set; }
    }
}
